import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#0f0d12",
        "secondary-container": "#ebddf7",
        "secondary-fixed-dim": "#dcd0e9",
        "on-surface-variant": "#625d67",
        "on-background": "#35313a",
        "primary-fixed-dim": "#aa7cf0",
        "secondary-dim": "#584f64",
        "on-primary": "#fef7ff",
        "on-surface": "#35313a",
        "on-secondary-fixed": "#443c50",
        "on-secondary": "#fef7ff",
        "on-tertiary-fixed": "#4e2740",
        "surface-variant": "#e8e0ec",
        "surface-container-low": "#f9f1fa",
        "primary-dim": "#6738aa",
        "surface-dim": "#dfd7e3",
        "secondary-fixed": "#ebddf7",
        "error-container": "#f97386",
        "on-secondary-fixed-variant": "#61586d",
        "surface-bright": "#fef7fe",
        "inverse-on-surface": "#a09ba1",
        "primary-fixed": "#b889ff",
        "error": "#a8364b",
        "tertiary-dim": "#714560",
        "background": "#fef7fe",
        "on-tertiary-container": "#643a54",
        "surface-tint": "#7446b7",
        "inverse-primary": "#b889ff",
        "surface": "#fef7fe",
        "on-tertiary": "#fff7f8",
        "tertiary-fixed": "#fac1e1",
        "outline-variant": "#b7afbb",
        "primary-container": "#b889ff",
        "outline": "#7f7883",
        "tertiary-container": "#fac1e1",
        "primary": "#7446b7",
        "on-error": "#fff7f7",
        "tertiary-fixed-dim": "#ecb4d2",
        "on-primary-fixed-variant": "#3e007e",
        "secondary": "#655b70",
        "on-tertiary-fixed-variant": "#6e435d",
        "error-dim": "#6b0221",
        "on-error-container": "#6e0523",
        "surface-container-highest": "#e8e0ec",
        "tertiary": "#7e516c",
        "surface-container": "#f3ebf5",
        "on-secondary-container": "#574e63",
        "surface-container-high": "#ede6f0",
        "on-primary-container": "#320067",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#000000",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      boxShadow: {
        editorial: "0px 10px 30px rgba(74, 20, 140, 0.04)",
        "editorial-md": "0px 10px 30px rgba(74, 20, 140, 0.1)",
        "editorial-lg": "0px 10px 30px rgba(74, 20, 140, 0.3)",
      },
    },
  },
  plugins: [],
};

export default config;
